spring.application.name=paymentService
spring.mvc.servlet.path=/api
server.port=${PAYMENTSERVICE_PORT}

#Info
info.app.name=Job Portal - Payment Service
info.app.description=Payment Service (Job Application Portal) by Akshat
info.app.version=${PAYMENTSERVICE_VERSION}

#Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Actuaor
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoint.shutdown.enabled=true
server.shutdown=graceful

#Cache (Redis)
spring.cache.type=redis
spring.data.redis.host=redis
spring.data.redis.port=${REDIS_PORT}
spring.cache.cache-name=${REDIS_CACHE_NAME}

#Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#Payment Gateway (Razorpay)
razorpay.api.key=${PAYMENTSERVICE_RAZORPAY_KEY}
razorpay.api.secret=${PAYMENTSERVICE_RAZORPAY_SECRET}
razorpay.webhook.secret=${PAYMENTSERVICE_RAZORPAY_WEBHOOK_SECRET}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_SERVERS}
spring.kafka.consumer.group-id=${PAYMENTSERVICE_KAFKA_GROUP_ID}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.listener.missing-topics-fatal=false
logging.level.org.springframework.kafka=DEBUG

