spring.application.name=userService
spring.mvc.servlet.path=/api
server.port=${USERSERVICE_PORT}

#Info
info.app.name=Job Portal - User Service
info.app.description=User Service (Job Application Portal) by Akshat
info.app.version=${USERSERVICE_VERSION}

#Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.validationTimeout=5000
spring.datasource.hikari.maximumPoolSize=5
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Actuaor
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoint.shutdown.enabled=true
server.shutdown=graceful

#Security
jwt.secret.key=${USERSERVICE_JWT_KEY}
jwt.token.expiration=${USERSERVICE_JWT_EXPIRATION}

#Cache (Redis)
spring.cache.type=redis
spring.data.redis.host=redis
spring.data.redis.port=${REDIS_PORT}
spring.cache.cache-name=${REDIS_CACHE_NAME}

#Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true