spring.application.name=orderService
spring.mvc.servlet.path=/api
server.port=${SERVER_PORT:0}

#Info
info.app.name=Job Portal - Order Service
info.app.description=Order Service (Job Application Portal) by Akshat
info.app.version=1.0.0

#Database
spring.datasource.url=jdbc:mysql://localhost:3306/jobportal
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Actuaor
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoint.shutdown.enabled=true
server.shutdown=graceful

#Cache (Redis)
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.cache-name=jobportal

#Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=orderService-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.listener.missing-topics-fatal=false
